import {chromium} from '/Users/zhoulin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
const out=new URL('./evidence/',import.meta.url).pathname;
const b=await chromium.launch({headless:true,executablePath:'/Users/zhoulin/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-x64/chrome-headless-shell'});
const p=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:3044');
await p.getByRole('heading',{name:'我的交易室',exact:true}).waitFor({timeout:60000});
await p.getByRole('combobox',{name:'报告计价',exact:true}).selectOption('CNY');
await p.getByRole('tablist',{name:'交易室期间',exact:true}).getByRole('tab',{name:'全部',exact:true}).click();
await p.getByRole('heading',{name:'历史交易与复盘',exact:true}).scrollIntoViewIfNeeded();
await p.getByRole('img',{name:'累计盈亏趋势图',exact:true}).waitFor();
const hit=p.locator('[data-chart-role="point-hit-area"]').last();
await hit.focus();await hit.press('Enter');
await p.getByRole('status',{name:'趋势点详情',exact:true}).waitFor();
const detail=await p.getByRole('status',{name:'趋势点详情',exact:true}).innerText();
if(detail.length<10)throw new Error('Missing visible real point detail');
await p.setViewportSize({width:1920,height:1080});
await p.waitForTimeout(350);
await p.setViewportSize({width:1440,height:1000});
await p.waitForTimeout(350);
await p.screenshot({path:out+'minimal-history.png'});
const data=await p.locator('svg[role="img"]').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),m=e.getScreenCTM();return {label:e.getAttribute('aria-label'),width:r.width,height:r.height,viewBox:e.getAttribute('viewBox'),ratio:m.a/m.d}}));
const history=await p.locator('[aria-label="历史交易与复盘"]').innerText();
await p.getByRole('heading',{name:'我的交易室',exact:true}).scrollIntoViewIfNeeded();
await p.screenshot({path:out+'minimal-room.png'});
await fs.writeFile(out+'minimal-journey.json',JSON.stringify({detail,data,errors,historySummary:history.slice(0,350),accountOptions:await p.getByRole('combobox',{name:'账户范围',exact:true}).locator('option').count()},null,2));
console.log(JSON.stringify({detail,data,errors,historySummary:history.slice(0,350)},null,2));
await b.close();
