import { chromium } from '/Users/zhoulin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
const out=new URL('./',import.meta.url).pathname;
const browser=await chromium.launch({headless:true,executablePath:"/Users/zhoulin/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-x64/chrome-headless-shell"});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.on('pageerror',e=>console.log('PAGEERROR',e.message));
await page.goto('http://127.0.0.1:3044');
await page.getByRole('heading',{name:'我的交易室',exact:true}).waitFor({timeout:90000});
await page.getByRole('combobox',{name:'报告计价',exact:true}).selectOption('CNY');
await page.getByRole('tab',{name:'今年至今',exact:true}).click();
await page.getByRole('img',{name:'累计盈亏趋势图',exact:true}).waitFor();
const measure=()=>page.locator('svg[role="img"]').evaluateAll(es=>es.map(e=>{let b=e.getBoundingClientRect(),m=e.getScreenCTM(),s=getComputedStyle(e);return {label:e.getAttribute('aria-label'),width:b.width,height:b.height,viewBox:e.getAttribute('viewBox'),preserve:e.getAttribute('preserveAspectRatio'),scaleX:m.a,scaleY:m.d,ratio:m.a/m.d,cssHeight:s.height,circles:e.querySelectorAll('circle').length,texts:e.querySelectorAll('text').length}}));
const measurements=await measure();
console.log(JSON.stringify(measurements,null,2));
await fs.writeFile(out+'initial-measurements.json',JSON.stringify(measurements,null,2));
await page.getByRole('img',{name:'累计盈亏趋势图',exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:out+'history-1440.png'});
await page.getByRole('region',{name:'当前持仓',exact:true}).screenshot({path:out+'holdings-1440.png'}).catch(async()=>await page.locator('section[aria-label="当前持仓"]').screenshot({path:out+'holdings-1440.png'}));
await page.locator('section[aria-label="历史持仓估值"]').screenshot({path:out+'holding-chart-1440.png'});
await page.locator('section[aria-label="当前持仓资产分布"]').screenshot({path:out+'allocation-1440.png'});
await browser.close();
const failures=measurements.filter(x=>(x.texts||x.circles)&&Math.abs(x.ratio-1)>.05);
for(const x of failures)console.log(`FAIL non-uniform SVG ${x.label}: sx=${x.scaleX.toFixed(3)} sy=${x.scaleY.toFixed(3)} ratio=${x.ratio.toFixed(3)}`);
process.exitCode=failures.length?1:0;
