import { afterEach, describe, expect, it, vi } from "vitest";
const { getReview, getReviews, getReviewStates, getTagSuggestions, putReview, putReviewState, putTagSuggestion, openSqliteDatabase } = vi.hoisted(() => ({ getReview: vi.fn(), getReviews: vi.fn(), getReviewStates: vi.fn(() => []), getTagSuggestions: vi.fn(), putReview: vi.fn(), putReviewState: vi.fn(), putTagSuggestion: vi.fn(), openSqliteDatabase: vi.fn() }));
vi.mock("../../../lib/storage/sqlite-store", () => ({ getSqliteStore: vi.fn(() => ({ getReview, getReviews, getReviewStates, getTagSuggestions, putReview, putReviewState, putTagSuggestion })) })); vi.mock("../../../../db/sqlite", () => ({ openSqliteDatabase }));
import { GET, PUT } from "./route";
const review = { version: 1, episodeId: "ep", instrumentId: "HK:700", updatedAt: "2025-01-01T00:00:00Z", plan: { thesis: "", expectedPath: "", invalidationCondition: "", targetRange: "", plannedRiskAmount: "", confidence: null }, review: { decisionQuality: null, executionQuality: null, riskManagement: "", psychology: "", reusableRule: "", completed: false }, confirmedTagIds: [] };
afterEach(() => vi.clearAllMocks());
describe("storage reviews route", () => {
  it("reads an episode and upserts a review", async () => { openSqliteDatabase.mockReturnValue({}); getReview.mockReturnValue(review); putReview.mockReturnValue(true); expect(await (await GET(new Request("http://localhost/api/storage/reviews?episodeId=ep"))).json()).toEqual(review); expect((await PUT(new Request("http://localhost", { method: "PUT", body: JSON.stringify(review) }))).status).toBe(200); });
  it("rejects malformed JSON and reports unknown instruments", async () => { expect((await PUT(new Request("http://localhost", { method: "PUT", body: "{" }))).status).toBe(400); openSqliteDatabase.mockReturnValue({}); putReview.mockImplementation(() => { throw new Error("Unknown instrument: bad"); }); expect((await PUT(new Request("http://localhost", { method: "PUT", body: JSON.stringify(review) }))).status).toBe(404); });
  it("accepts a tag suggestion and reports duplicate review conflicts", async () => { openSqliteDatabase.mockReturnValue({}); putReview.mockReturnValue(false); expect((await PUT(new Request("http://localhost", { method: "PUT", body: JSON.stringify(review) }))).status).toBe(409); const suggestion = { version: 1, id: "tag", episodeId: "ep", instrumentId: "HK:700", tagId: "entry-20d-breakout", finalTagId: null, ruleId: "entry-20d-breakout", ruleVersion: 1, status: "suggested", suggestedAt: "2025-01-01", decidedAt: null, evidence: [] }; expect((await PUT(new Request("http://localhost", { method: "PUT", body: JSON.stringify(suggestion) }))).status).toBe(200); expect(putTagSuggestion).toHaveBeenCalledWith(suggestion); });
  it("reads and writes review state drawings", async () => { openSqliteDatabase.mockReturnValue({}); const state = { version: 2, episodeId: "ep", replayCursor: "2025-01-01T00:00:00Z", timeframe: "1D", activePanelTab: "notes", drawings: [] }; getReviewStates.mockReturnValue([state] as never); expect(await (await GET(new Request("http://localhost/api/storage/reviews?stateFor=ep"))).json()).toEqual(state); expect((await PUT(new Request("http://localhost", { method: "PUT", body: JSON.stringify(state) }))).status).toBe(200); expect(putReviewState).toHaveBeenCalledWith(state); });
});
